import { DONATION_STATUS } from "../../../constants/enums.js";

/** Statuses a donor can cancel from */
export const DONOR_CANCELLABLE_STATUSES = new Set([
  DONATION_STATUS.PENDING,
  DONATION_STATUS.VERIFIED,
  DONATION_STATUS.NGO_ACCEPTED,
]);

/** Statuses considered active (in workflow) */
export const ACTIVE_DONATION_STATUSES = new Set([
  DONATION_STATUS.PENDING,
  DONATION_STATUS.VERIFIED,
  DONATION_STATUS.NGO_ACCEPTED,
  DONATION_STATUS.VOLUNTEER_ASSIGNED,
  DONATION_STATUS.PICKUP_SCHEDULED,
  DONATION_STATUS.PICKED_UP,
  DONATION_STATUS.IN_TRANSIT,
  DONATION_STATUS.DELIVERED,
]);

/** Statuses considered completed history */
export const COMPLETED_DONATION_STATUSES = new Set([
  DONATION_STATUS.COMPLETED,
  DONATION_STATUS.REJECTED,
  DONATION_STATUS.CANCELLED,
  DONATION_STATUS.EXPIRED,
]);

/** Statuses where donor can edit donation details */
export const DONOR_EDITABLE_STATUSES = new Set([
  DONATION_STATUS.PENDING,
]);

export const STATUS_LABELS = {
  [DONATION_STATUS.PENDING]: "Pending",
  [DONATION_STATUS.VERIFIED]: "Verified",
  [DONATION_STATUS.NGO_ACCEPTED]: "NGO Accepted",
  [DONATION_STATUS.VOLUNTEER_ASSIGNED]: "Volunteer Assigned",
  [DONATION_STATUS.PICKUP_SCHEDULED]: "Pickup Scheduled",
  [DONATION_STATUS.PICKED_UP]: "Picked Up",
  [DONATION_STATUS.IN_TRANSIT]: "In Transit",
  [DONATION_STATUS.DELIVERED]: "Delivered",
  [DONATION_STATUS.COMPLETED]: "Completed",
  [DONATION_STATUS.REJECTED]: "Rejected",
  [DONATION_STATUS.CANCELLED]: "Cancelled",
  [DONATION_STATUS.EXPIRED]: "Expired",
};

export default {
  DONOR_CANCELLABLE_STATUSES,
  ACTIVE_DONATION_STATUSES,
  COMPLETED_DONATION_STATUSES,
  DONOR_EDITABLE_STATUSES,
  STATUS_LABELS,
};
